language: python

python:
- '3.5'

install:
- pip install -r dev-requirements.txt

script:
- pytest tests/ -v
- pycodestyle gaia_communication/*

notification:
  email: false

before_deploy:
  - echo 'Beggining deploy...'
  - python3 setup.py build
  - python3 setup.py sdist bdist_wheel

deploy:
  - provider: script
    script: bash deploy.sh deploy
    on:
      branch: master
